//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class Product_DBEntities : DbContext
    {
        public Product_DBEntities()
            : base("name=Product_DBEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }

        //// public System.Data.Entity.DbSet<BusinessEntities.ReviewEntity> ReviewEntities { get; set; }

        //// public System.Data.Entity.DbSet<BusinessEntities.ProductEntity> ProductEntities { get; set; }
    }
}
